#ifndef PTR_IDENTIFIER_ENUMS
#define PTR_IDENTIFIER_ENUMS

enum class PTR_IDENTIFIER
{
	INPUT_HANDLER_PTR,
	OBJ_CONTAINER_PTR,
	OBJ_CREATION_QUEUE_PTR,
	OBJ_DESTRUCTION_QUEUE_PTR,
	IMG_CREATION_QUEUE_PTR,
	IMG_DESTRUCTION_QUEUE_PTR,
	PUSH_UPDATE_QUEUE_PTR,
	WINDOW_PTR,
	SOUND_ENGINE_PTR,
};

#endif //PTR_IDENTIFIER_ENUMS
